### PR TITLE
Fix channel being ignored on query

### LINKED ISSUE #1737: Simple search channel parameter is not working
EE 6.2.2
PHP: 7.4.16

I'm trying to exclude entries from a certain channel appearing in the search results.

I’ve added the channel not parameter to the simple search but results from the channel are been returned on the results page.

```
{exp:search:simple_form channel="not asset" status="Protected|open" search_in="entries" result_page="bca/search-results"}
         <div class="mb-3">
         <label for="keywords" class="form-label">Search</label>
         <input type="text" class="form-control mb-2" name="keywords" id="keywords" placeholder="Search term">
         <input type="submit" value="Search" class="btn btn-bca-blue">
        </div>
  {/exp:search:simple_form}
```

I've also tried getting results from a certain channel `channel="news_blog"` and this also returns results from outside of the set channel.

### PR DESCRIPTION
**Pull request by robsonsobral**
## Overview

Simple search channel parameter is not working

Resolves [#1737](https://github.com/ExpressionEngine/ExpressionEngine/issues/1737).

## Nature of This Change

- [x] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by intoeetive — DISMISSED** [review]
@robsonsobral thank you for catching this so quickly!

**Comment by robsonsobral** [comment]
I'm so sorry for this regression. I didn't sleep until I fixed it.

I gonna review everything one more time.

I'm so sorry, @intoeetive and @TomJaeger .

**Review by TomJaeger — DISMISSED** [review]

**Comment by robsonsobral** [comment]
I confess I've no idea on how to edit the changelog files.

Let's fix this conflict.

**Comment by robinsowell** [comment]
WOOT- works for me locally!

**Review by TomJaeger — APPROVED** [review]

**Pull request merged**
