### PR TITLE
Resolved #3844 where applying `search:field="IS_EMPTY"` parameter to Grid field would cause PHP warning

### LINKED ISSUE #3844: Live preview error with grid field search parameter and IS_EMPTY
So grid fields let you use a search parameter like the channel entry tag.

```
{blog_image search:caption="=blog"}
					<figure>
						<img src="{blog_image:image}" alt="{blog_image:caption:attr_safe}">
						<figcaption>{blog_image:caption}</figcaption>
					</figure>
				{/blog_image}
```
This works- frontend and in live preview.  But if you so:

```
{blog_image search:caption="IS_EMPTY"}
```
It works on the frontend, but the preview gives you an error:
```
Warning
Undefined array key "col_id_12!="""
ee/legacy/models/grid_model.php, line 509
```

### PR DESCRIPTION
**Pull request by intoeetive**
Resolved #3844 where applying `search:field="IS_EMPTY"` parameter to Grid field would cause PHP warning

### CODE REVIEW

**Comment by robinsowell** [comment]
@intoeetive The user tried this patch, and it didn't solve it.  So then I tested- I'm running EE 7.4 dp31 and I just manually applied the changed code to that.  I still have the problem as well- works fine on frontend, but in preview, the conditional doesn't actually work plus i get the php error in my logs.

Here's a comparison of results on frontend vs preview:

Screenshot 2023-12-04 at 12 48 36 PMa

And here's my error log- note, it's only throwing the error in preview:

```
ERROR - 2023-12-04 12:47:05 --> Severity: E_WARNING  --> Undefined array key "col_id_12!=""" /Users/robinsowell/Sites/6live/system/ee/legacy/models/grid_model.php 516
ERROR - 2023-12-04 12:47:05 --> Severity: E_WARNING  --> Undefined array key "col_id_12!=""" /Users/robinsowell/Sites/6live/system/ee/legacy/models/grid_model.php 516
```

**Comment by intoeetive** [comment]
@robinsowell works perfectly for me if I switch the branch (also nothing in error logs)

What is the exact template code that you're using?

**Comment by robinsowell** [comment]
Here's my template:
```
<h2>No search on grid</h2>
{exp:channel:entries}
<h4>{title}</h4>

{blog_image}
url: {blog_image:image}<br>
cap: {blog_image:caption}
{/blog_image}
				
{/exp:channel:entries}	

<h2>Search on caption NOT empty in grid</h2>
{exp:channel:entries}
<h4>{title}</h4>

{blog_image search:caption="not IS_EMPTY"}
url: {blog_image:image}<br>
cap: {blog_image:caption}
{/blog_image}
				
{/exp:channel:entries}	

<h2>Search on caption IS empty in grid</h2>
{exp:channel:entries}
<h4>{title}</h4>

{blog_image search:caption="IS_EMPTY"}
url: {blog_image:image}<br>
cap: {blog_image:caption}
{/blog_image}
				
{/exp:channel:entries}
```

Running 7.4 dp33. I went in and manually added the code from the 1 file changed- basically, made these two changes:

Screenshot 2023-12-06 at 4 23 57 PM

Screenshot 2023-12-06 at 4 25 09 PM


Note- using Structure, if it matters.

I get different results frontend vs preview, plus I still throw the error in preview.

**Comment by intoeetive** [comment]
@robinsowell thank you - `not IS_EMPTY` case was different, and I did not check it.

The fix is pushed (I also merged 7.4 branch to just make sure we're on same page... the changed files are `legacy\models\channel_model.php` and `legacy\models\grid_model.php`)

**Comment by robinsowell** [comment]
Argh- yell if I should put in a new bug.  So- it checked out fine for me in tests, but it did not for the user.  He's got fluid>grid and he's checking a toggle.  Results are different in preview vs live page.  Template looks like:

```
{exp:channel:entries stuff}
<h3>{title}</h3>

      {landing_content}

            {landing_content:downloads}
            
            {content}
            pure toggle is irish: {content:irish}<br>
            {/content}
            
 
                  {content search:irish="IS_EMPTY"}
                        ENGLISH<br>
                   {/content}

                   
                    {content search:irish="not IS_EMPTY"}
                         Gaeilge<br>
                     {/content}
					 
					 <hr>
					 
                    {content search:irish="IS_EMPTY"}
                       empty  {content:download}{content:download_title}<br>
                   {/content}
								
                     {content search:irish="not IS_EMPTY"}
                            not empty {content:download}{content:download_title}<br>

                     {/content}
 				
           {/landing_content:downloads}
      {/landing_content}	  

{/exp:channel:entries}
```

landing_content is a fluid field, downloads is a grid field, irish is a toggle.  In testing, irish is always coming back as not empty.  Live, it's correct.

Screenshot 2023-12-13 at 2 47 21 PM

@intoeetive

**Comment by intoeetive** [comment]
@robinsowell I don't think I can give a good fix for that one. The problem is that Toggle is sending "off" value as `0` - which is not empty. If we treat 0 as empty, then we can end up with having Number field treated improperly.

I would suggest instead of empty/not empty checks using strict comparisons `{content search:irish="0"}` and `{content search:irish="1"}`.

**Comment by robinsowell** [comment]
@intoeetive What's weird is it works on the frontend, just not in preview.  Though I agree, seems like a good quick fix for this use case.

**Review by bryannielsen — APPROVED** [review]

**Pull request merged**
