### PR TITLE
Resolved #2107 where Cookie Consents were not fully installed when updating from EE2

### LINKED ISSUE #2107: EE2 to EE6 Upgrade Breaking Member Consent Page
After upgrading from `EE v2.10.1` to `EE v6.3.4` with the single update, we ran into an issue where the Member Consent page would throw errors as noted below. To fix the issue i had to copy the content in `Functionality Cookies -> Request` from another site freshly updated to EE6 into my project site and hit save, which fixed the issue.

Make sure to mention what page you are on, if this is issue in Control Panel - provide the URL (domain name can be removed)
`/system/index.php?/cp/members/profile/consent&id=444`

Add a screenshot. If error backtrace is available, provide it. 
```
Error Caught
Call to a member function format() on null
ee/ExpressionEngine/View/account/consents.php:52

Stack Trace: Please include when reporting this error
#0 system\ee\ExpressionEngine\Service\View\View.php(137): include()
#1 system\ee\ExpressionEngine\Service\View\View.php(106): ExpressionEngine\Service\View\View->parse('D:\\webdev\\EE-De...', Array)
#2 system\ee\legacy\libraries\View.php(40): ExpressionEngine\Service\View\View->render(Array)
#3 system\ee\legacy\libraries\Cp.php(339): View->render('account/consent...', Array, false)
#4 system\ee\ExpressionEngine\Controller\Members\Profile\Consent.php(178): Cp->render('account/consent...', Array)
#5 [internal function]: ExpressionEngine\Controller\Members\Profile\Consent->index()
#6 system\ee\ExpressionEngine\Core\Core.php(255): call_user_func_array(Array, Array)
#7 system\ee\ExpressionEngine\Core\Core.php(111): ExpressionEngine\Core\Core->runController(Array)
#8 system\ee\ExpressionEngine\Boot\boot.php(161): ExpressionEngine\Core\Core->run(Object(ExpressionEngine\Core\Request))
#9 admin.php(144): require_once('D:\\webdev\\EE-De...')
#9 admin.php(144): require_once('D:\\webdev\\EE-De...')
```
Exactly the same issue as [noted here](https://expressionengine.com/forums/topic/253264/error-consent-settings-bug)

Tell us about your environment (EE version including beta number, PHP/MySQL version, web server, OS etc)
`PHP v7.4.29`
`MariaDB v10.3.28`

### PR DESCRIPTION
**Pull request by intoeetive**
Resolved #2107 where Cookie Consents were not fully installed when updating from EE2

Update EE to 7.2.1

### CODE REVIEW

**Comment by TomJaeger** [comment]
@intoeetive I took a peek at this one.  If a site is already upgraded and has this issue, how can we apply the fix?

**Comment by intoeetive** [comment]
You can clean up consent_requests and consent_requests version tables and rerun the update. But in practice, it's much easier to copy the records from another sites, just like OP did

**Comment by matthewjohns0n** [comment]
These tests are failing and it looks like it has to do with updating from EE2->EE7, so I'm pushing this to 7.2.x.

**Comment by intoeetive** [comment]
I think this is one of reasons Tom wants this release today. Can you look
into fixing?

пн, 21 лист. 2022, 21:05 користувач Matt Johnson ***@***.***>
пише:

**Review by robinsowell — DISMISSED** [review]
Fixed it for me.

**Comment by robinsowell** [comment]
Fixed it for me, php 7.4.  Soooo

**Comment by matthewjohns0n** [comment]
Just noting that tests were only failing because the versions were mismatched. I had Andy run the version_bump command update all the files to 7.2.2 and tests are now passing.

**Review by matthewjohns0n — APPROVED** [review]

**Pull request merged**
