### PR TITLE
Bug/188 image manipulation warnings

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

Adds integer casting for padding and offset pixels coming in on image manipulations.

Resolves [#188](https://github.com/ExpressionEngine/ExpressionEngine/issues/188).

## Nature of This Change

- [X] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by robsonsobral** [comment]
Hi, @dougblackjr ! There's still a string witch need to be turned into integer: `$this->wm_use_opacity`.

**Comment by dougblackjr** [comment]
@robsonsobral I believe that casts as a bool. Is there an issue specifically related to that one that you're running in to?

**Comment by robsonsobral** [comment]
I thought the same, until...

```
<div class="err-wrap warn">
	<h1>Warning</h1>
	<h2>imagecopymerge() expects parameter 9 to be integer, string given</h2>
	<p>ee/legacy/libraries/Image_lib.php, line 1011</p>
	<ul>
		<li><b>Severity</b>: E_WARNING</li>
	</ul>
</div>
```

**Comment by dougblackjr** [comment]
@robsonsobral Wow, good catch! Just pushed a change. I believe this is how it is coming in as input, let me know if you see any other issue on this.

**Comment by robsonsobral** [comment]
Actually, @marchimedia is the one who found it.

**Comment by dougblackjr** [comment]
Closing in favor of #386

**Pull request closed without merging**
