### PR TITLE
Introduced ability for custom fieldtypes to be used in Member profiles; #715

### LINKED ISSUE #715: More fields type for members section
It will be awesome to have the same fields management for members, like channels.
Missing Checkboxes right now and File for a project.

### LINKED ISSUE #3763: Emails in custom member text fields are getting encrypted
EE 7.3.12
A custom member field, a simple text input, if filled with an email address gets encrypted like this:

`<span data-eeEncEmail_LGHQuxgspc='1'>.(JavaScript must be enabled to view this email address)</span><script>/*<![CDATA[*/var out = '',el = document.getElementsByTagName('span'),l = ['>','a','/','<',' 109',' 111',' 99',' 46',' 108',' 105',' 97',' 109',' 103',' 64',' 103',' 111',' 100',' 101',' 114',' 105',' 102',' 103',' 111',' 100','>','\"',' 109',' 111',' 99',' 46',' 108',' 105',' 97',' 109',' 103',' 64',' 103',' 111',' 100',' 101',' 114',' 105',' 102',' 103',' 111',' 100',':','o','t','l','i','a','m','\"','=','f','e','r','h','a ','<'],i = l.length,j = el.length;while (--i >= 0)out += unescape(l[i].replace(/^\s\s*/, '&#'));while (--j >= 0)if (el[j].getAttribute('data-eeEncEmail_LGHQuxgspc'))el[j].innerHTML = out;/*]]>*/</script>`

How to reproduce:
1. Create a text input member field.
2. Go to your profile in CP and type in any email address
3. Put this code in any template and open it: `{exp:member:custom_profile_data} {text_field} {/exp:member:custom_profile_data}`

### PR DESCRIPTION
**Pull request by intoeetive**
Introduced ability for custom fieldtypes to be used in Member profiles; closes #715

Also fixes validation for custom fields, so that same names could not be used for channel field and member field

Docs: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/584

also closes #3763

### CODE REVIEW

**Comment by dougblackjr** [comment]
VERY excited for this one. Thanks @intoeetive!

**Comment by TomJaeger** [comment]
FYI looks like this one has conflicts....

**Comment by litzinger** [comment]
How does this work with add-ons utilizing hooks in field types, e.g. Relationship and Grid? If a Grid field is added as a member field, does the hook have any context to if it is querying entry data or member data?

I assume field types need to opt-in like they do now with the content_type?

I'm mostly inquiring because I'm curious how this will affect Publisher so I can be ready for the changes. For example if someone adds a Grid field to a member profile, Publisher's hooks are going to assume it's working with an entry (and thus an entry_id), not a member.

**Comment by intoeetive** [comment]
@litzinger from the docs: 

> If a fieldtype is also compatible with other content types (such as `MemberField` model that represents Custom Member Fields) then the model name needs to be specified in `use` array.
> 
>     'use' => array(
>       'MemberField'
>     )

https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/584/files#diff-d05e939e3709644c2f4073a6b4c964cf4b2d31278e30da7ff26bdea4554e880bR129-R133

Long story short, the fieldtypes need to declare that they are compatible with Member Custom Fields. By default, we assume they are NOT compatible. The way Relationships and Grids were build years ago, they require entry_id and so can't be used for anything but entries

**Review by robinsowell — APPROVED** [review]

**Pull request merged**
