### PR TITLE
Resolved #3222 where File icon in File field does not match field type

### LINKED ISSUE #3222: File icon in File field does not match field type
In the File Manager the icons for  files that are not images vary depending on file type - document, archive etc.

However when you select file in File field, it's displays the generic icon, without respecting file type 
image

### PR DESCRIPTION
**Pull request by Yulyaswan**
Resolved #3222 where File icon in File field does not match field type
EECORE-2213

### CODE REVIEW

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan I think we're missing `fa-file-video` here

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan if I select 'doc' file that's not in the list of mimes (in my case '.md' file) I get no icon at all. Probably an extra `else` is needed

Also, can we make it so that icon lines would be grey (like they are in file manager) and not black?

**Comment by intoeetive** [comment]
@Yulyaswan I am so sorry :)

If I select a file, then change my mind, click "edit" pencil and select another file, I get 2 icons: 
image

**Comment by Yulyaswan** [comment]
@intoeetive fixed :)

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan I still see this behaviour.
Steps:
- have a field with image in it
- edit the field data, select text file. The image icon removed, text icon added
- edit the field data, select zip fil. The zip icon is added next to next icon

**Comment by Yulyaswan** [comment]
https://user-images.githubusercontent.com/23382425/231180074-8b0f5b4b-9063-4ad2-b500-ae623955adb9.mov

could it be cache? @intoeetive

**Comment by intoeetive** [comment]
@Yulyaswan it could be, but it is not :)
Use the "edit" button (pencil), not "remove"(x)

**Comment by Yulyaswan** [comment]
@intoeetive should be ok now

**Review by intoeetive — APPROVED** [review]
👍

**Pull request merged**
