### PR TITLE
Improve UI when managing categories on publish form, EECORE-1472

### PR DESCRIPTION
**Pull request by Yulyaswan**
Added edit icon and hover to make the editable view more user-friendly for managing categories on publish form	

EECORE-1472

### CODE REVIEW

**Review by intoeetive — CHANGES_REQUESTED** [review]
Overall looks good to me. However when hovering sub-category the parent category is highlighted as well, which I don't think is correct

image

**Comment by Yulyaswan** [comment]
@intoeetive fixed this part, added video to the task

**Comment by TomJaeger** [comment]
Had a quick conversation with @ajohnson on this one yesterday as well.  He's reviewing currently.

**Comment by ajohnson** [comment]
@Yulyaswan Left you a comment in the Jira issue: https://packettide.atlassian.net/browse/EECORE-1472?focusedCommentId=15263

Thanks!

**Review by intoeetive — APPROVED** [review]
see below for an issue found

**Review by intoeetive — CHANGES_REQUESTED** [review]
Unfortunately Status editing tab (when editing Channel) got broken because it's using same shared component
image

**Comment by Yulyaswan** [comment]
fixed 
Edit Channel ExpressionEngine 🔊 2021-11-11 at 3 07 13 PM

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan looks good, but the tests are still failing. I assume you just need to update selectors in test scripts? (please message me if you want to have a call and walkthrough on how testing works)

**Review by intoeetive — DISMISSED** [review]

**Review by intoeetive — APPROVED** [review]

**Pull request merged**
