### PR TITLE
Resolved #3384 where Reassign Entries dialog did not populate when deleting a member

### LINKED ISSUE #3384: When Deleting a Member, Member Select to Reassign Entries does not populate
**Description of the problem**

EE7 site that we're trying to delete a member. When trying to delete the member, it pulls up the modal to reassign entries. However, it does not populate the list of Members.

**How To Reproduce**
1. Create site with 1000+ members (it's a LOT).
2. Go to delete one of them.
3. View select for reassignment

**Error Messages**
No error messages. No error in the ajax call, nothing in the console.

**Screenshots / Videos / Template Code**
Screenshot from 2023-05-11 13-18-43

I did see the `data-react-select` serialized data on the element in the code. That output a properly form object when using unserialize:
Screenshot from 2023-05-11 13-23-19

**Environment Details:**
 - Version: 7.2.19
 - PHP Version 8.0.x
 - MySQL Version 8.0
 - OS: Linux
 - Web Server: nginx, but prod has same on Apache

### PR DESCRIPTION
**Pull request by Yulyaswan**
Resolved #3384 where Reassign Entries dialog did not populate when deleting a member

### CODE REVIEW

**Review by robinsowell — APPROVED** [review]
Yay- fixed it for me! Came up in support.

**Comment by pyrobob83** [comment]
I came here to add this issue but see it's already been raised and even addressed, just doesn't look like it's been merged... is there an ETA on when this might get into a public release?

**Comment by TomJaeger** [comment]
@pyrobob83 Just added it to our next release milestone... Any chance you happened to pull in the fix and could confirm it's working?

**Comment by pyrobob83** [comment]
@TomJaeger I haven't had a chance, but will see if I can make the time to try it, but I trust Yulya and Robin!

**Pull request merged**
