### PR TITLE
Feature/384 add relative url to url field

### LINKED ISSUE #384: Add relative "/" option to URL field under Field Options > Allowed URL Schemes
Sometimes in a URL field, we need the ability to enter a URL relative to the site but we can't - the only options are the typical protocols and a // option, but none of these options allow the user to add a link to say:

`/my-page#my-anchor`

Please add an option for a URL scheme that starts with a single / to the 'Allowed URL Schemes' checkbox list in the Field Options when setting up a URL field.

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

Allows for URL fields to have single slash relative links, such as `/test`

Resolves [#384](https://github.com/ExpressionEngine/ExpressionEngine/issues/384).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [X] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/404

### CODE REVIEW

**Comment by dougblackjr** [comment]
@intoeetive Looks like this is failing here:

```
You passed the --record flag but this project has not been setup to record.

This project is missing the 'projectId' inside of 'cypress.json'.

We cannot uniquely identify this project without this id.

You need to setup this project to record. This will generate a unique 'projectId'.

Alternatively if you omit the --record flag this project will run without recording.

https://on.cypress.io/recording-project-runs
Test run failed, code 1
More information might be available above
Cypress module has returned the following error message:
Could not find Cypress test run results
Error: Could not find Cypress test run results
```

Is this something I need to add? Or am I misreading this?

**Comment by robsonsobral** [comment]
@dougblackjr , the option should be named **Root** Relative URL.

**Comment by intoeetive** [comment]
@bryannielsen any ideas here?

**Comment by dougblackjr** [comment]
@intoeetive @bryannielsen Thoughts on the error in the testing? I have the same issue on #1857

**Review by intoeetive — APPROVED** [review]

**Review by intoeetive — CHANGES_REQUESTED** [review]
@dougblackjr looks like it also needs an update in tests, specifically in `field_combinations.ee6.js` file

**Review by intoeetive — APPROVED** [review]

**Pull request merged**
