### PR TITLE
change login extension hook placement fot CP logins

### PR DESCRIPTION
**Pull request by stephengalbraith**
## Overview

While working on a small extension to allow users to login from the front-end via their email instead of username, I noticed that unlike in the front-end login form the hook for the CP gets called after the username variable is set, effectively not allowing the hook to be used to its full potential.

For example in system/ee/ExpressionEngine/Addons/member/mod.member_auth.php where the 'member_member_login_start' is called before setting the variables that get checked.

Resolves [#NN](https://github.com/ExpressionEngine/ExpressionEngine/issues/NN).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [x] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pulls/NNN

### CODE REVIEW

**Review by intoeetive — COMMENTED** [review]
I wonder if the existing code order was intentional, not allowing to change username on CP logins as a security measure.

@matthewjohns0n I'd like your input here as well

**Comment by matthewjohns0n** [comment]
I think this change makes sense. @intoeetive can we run the tests again before we merge, since they failed?

**Comment by intoeetive** [comment]
@matthewjohns0n we probably need to merge in latest 6.dev to run the tests, as the testing workflow has been updated

**Comment by intoeetive** [comment]
@stephengalbraith can you pull in latest `ExpressionEngine:6.dev` and merged it into your branch? I tried to do it, but was not successful

**Comment by stephengalbraith** [comment]
@intoeetive it looks like my branch is equal to 6.dev now. If necessary, I can submit a new PR just in case there's something else going wrong since this was done in March

**Comment by intoeetive** [comment]
@stephengalbraith you need to pull 6.dev from EE repo origin (not your fork's origin) and then merged (so you'll need to add ExpressionEngine/ExpressionEngine as an extra remote)

**Comment by stephengalbraith** [comment]
Closed - see #1515

**Pull request closed without merging**
