### PR TITLE
Resolved #1624 where generating extensions using CLI could produce broken PHP code

### LINKED ISSUE #1624: Extension Generator in CLI may produce broken PHP for certain extensions
**Description of the problem**

The CLI add-on generator utilizes the extension hooks in the documentation, some of which are documented as sending in `$this` as the parameter. The add-on generator uses this in the enum, producing invalid PHP.

For example, I create an extension using the `sessions_end` hook:
Screenshot from 2021-12-08 08-47-47

The documentation states that `$this` is sent in:
Screenshot from 2021-12-08 08-49-25

However, this is invalid PHP:
Screenshot from 2021-12-08 08-51-05

**How To Reproduce**
1. Create an extension on the CLI utilizing a hook that has `$this` labeled as a parameter in the documentation.
2. Lint the created extension.

**Error Messages**
`PHP Fatal error: Cannot use $this as parameter`

**Possible Solution**
Change $this to $obj in the associated extension hooks.

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

Moves `$this` to `$obj` in the creation of extensions utilizing hooks documented to use $this.

Resolves [#1624](https://github.com/ExpressionEngine/ExpressionEngine/issues/1624).

## Nature of This Change

- [X] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by intoeetive** [comment]
@matthewjohns0n can you review?

**Review by matthewjohns0n — COMMENTED** [review]
The change looks good but it is failing tests. We might want to merge into `6.2.0` instead and run those tests again. I think there was something wrong with the tests that has been resolved since.

**Comment by matthewjohns0n** [comment]
@dougblackjr Can you merge the `6.2.0` branch into your branch and push? That will trigger the 6.2.0 tests to run.

**Comment by dougblackjr** [comment]
@matthewjohns0n Thanks Matt! Just merged and pushed

**Comment by dougblackjr** [comment]
@matthewjohns0n Just saw the tests are continuing to fail here, specifically the "Build EE for testing", around the asdf dependencies?

Screenshot from 2021-12-21 04-12-18

**Comment by dougblackjr** [comment]
@matthewjohns0n All tests passing now!

**Comment by intoeetive** [comment]
I believe this was closed by mistake

**Review by matthewjohns0n — APPROVED** [review]

**Review by bryannielsen — APPROVED** [review]

**Pull request merged**
