### PR TITLE
Allow module tabs to be displayed as columns in Entry Manager; #645

### LINKED ISSUE #645: Show Entry Link on Entry and Entries listing
Problem: A content editor cannot easily access the published entry's link anywhere, neither on the Entry edit page, or on the Entries listing page. The Preview feature is great, but a direct link to the published link, if it exists publicly, will be a very nice  enhancement that is probably easy to implement.

Here are some screenshots of how this can be shown:

**Entry page before, without external link **:

Screenshot 2020-11-17 at 10 04 27

**Entry page with external link**:

Screenshot 2020-11-17 at 10 25 13

**Entries listings**:

Showing link to published content if it exists
Screenshot 2020-11-17 at 10 31 19

### PR DESCRIPTION
**Pull request by intoeetive**
Allow module tabs to be displayed as columns in Entry Manager; closes #645

The `tab.module_name.php` files need to implement `renderTableCell` method - see Structure or Pages for an example

### CODE REVIEW

**Comment by TomJaeger** [comment]
Do we have a docs pr for this as well? @intoeetive

**Comment by intoeetive** [comment]
Docs added ==> https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/553

@bakin1999 we need to add this to EEHarbor modules that have tabs.

Starter for SEEO might look like (but certainly we need something better)
```
    public function renderTableCell($data, $field_id, $entry)
    {
        $entry_meta = $this->getEntryMeta($entry->entry_id);
        return json_encode($entry_meta);
    }
```

**Review by matthewjohns0n — APPROVED** [review]
Looks good from what I can tell 👍🏼

**Comment by lutzheckelmann** [comment]
I'm missing something, I can't output unescaped HTML.

Expample:

public function renderTableCell($data, $field_id, $entry)
{
    $entry_preview_link = sprintf("<a href=\"/article_live_look/%s\">Preview</a>", $entry->entry_id);
    return $entry_preview_link;
}

`// returns e.g. "&lt;a href="/article_live_look/89478"&gt;Preview&lt;/a&gt;"`

**Comment by lutzheckelmann** [comment]
> I'm missing something, I can't output unescaped HTML.
> 
> Expample:
> 
> public function renderTableCell($data, $field_id, $entry) { $entry_preview_link = sprintf("<a href="/article_live_look/%s">Preview", $entry->entry_id); return $entry_preview_link; }
> 
> `// returns e.g. "&lt;a href="/article_live_look/89478"&gt;Preview&lt;/a&gt;"`

Ok, got it. It's a time-consuming fun game to find information about expressionengine like this... ;) In case anyone stumbles upon this question, there is a table column configuration option "encode" which defaults to TRUE.

**Pull request merged**
