### PR TITLE
Fix validation of category fields

### LINKED ISSUE #1277: Wrong validation of category fields
I'm not sure this is a bug. When creating a category field, the validation of its name checks against previously [created fields of the entire site](https://github.com/ExpressionEngine/ExpressionEngine/blob/34d567e4022988a4b25018e5b1605222fa23f526/system/ee/ExpressionEngine/Model/Category/CategoryField.php#L48).

```php
'field_name' => 'required|alphaDash|unique[site_id]|validateNameIsNotReserved|maxLength[32]',
```

However, I think it should be against the same category group.

```php
'field_name' => 'required|alphaDash|unique[group_id]|validateNameIsNotReserved|maxLength[32]',
```

I tested and this change works. Am I right? Thank you!

I'm running eemcs 6.0.6.

### PR DESCRIPTION
**Pull request by robsonsobral**
## Overview

When creating a category field, the validation of its name checks against previously created fields of the entire site, instead of the same category group only.

Resolves [#1277](https://github.com/ExpressionEngine/ExpressionEngine/issues/1277).

## Nature of This Change

- [x] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

### CODE REVIEW

**Review by intoeetive — DISMISSED** [review]
I think this is safe change, so approving - but would like to have an extra eye on it.

Also, @robsonsobral - can you merge in latest `6.dev` to make the tests run?

**Comment by robsonsobral** [comment]
I'm doing rebases instead of merges because it's safer for who doesn't know the code deeply.

**Review by matthewjohns0n — APPROVED** [review]

**Review by robinsowell — COMMENTED** [review]
Looks good to me

**Comment by robinsowell** [comment]
I ran into a bit of a problem on the frontend.

I have 3 cat groups.  I created a custom category field called 'citation' in each of the groups.  Each of the cat groups is assigned to my 'Blog' channel.  Everything in the cp seems fine.

Screen Shot 2022-02-22 at 10 58 18 AM

But on the frontend, it looks like it's having trouble keeping straight which {citation} field belongs to which cat group.

```{exp:channel:categories channel="blog"}
    <a href="{path='channel/index'}">{category_name}</a>
    {citation}
{/exp:channel:categories}
```
Screen Shot 2022-02-22 at 11 39 29 AM

So- output of the 3 cat groups, but only the last one 'Cats group' is showing the value of its {citation} fields.  Other categories do have content in their citation field.  

Haven't mucked around with the categories tag pair in the channel entries tag, but anywhere we're parsing those and can have multiple groups likely needs a look.

**Comment by robsonsobral** [comment]
I don't love you anymore, @robinsowell .

Let's rewrite the categories fields parser!

**Comment by robinsowell** [comment]
LOL- I'm sorry!  I figured there was a decent chance it would work, but alas....

**Comment by robsonsobral** [comment]
I didn't get this error on category archive. Let's try again.

**Comment by robsonsobral** [comment]
Shouldn't we delay the next release until I clean up the mess I made?

**Pull request merged**
