### PR TITLE
Resolved #3456 where manipulated images could have wrong rotation

### LINKED ISSUE #3456: Uploaded images showing incorrect rotation
7.x issue

Basically, iphones use exif data to properly oriented images.  People upload an image that looks correctly oriented and it ends up sideways.

I know this has come up before and at one point 'fixed' but the fix no longer works and it's just not a good user experience, especially for non-technical users.  I believe any resizing/alteration loses exif and the image is just wrong.  

Here's the prior fix:
https://github.com/ExpressionEngine/ExpressionEngine/pull/277

Here's prior discussion:
https://github.com/ExpressionEngine/ExpressionEngine/issues/105

Here's 
an example- I'm also including a zip of the two files.  I was testing 7.3 and used the two test files in my tests- you can see the sideways orientation ends up sideways:

Screenshot 2023-05-25 at 11 39 45 AM

MAYBE it works with the original image (if browser reading exif) but the thumbs and file manips don't read it and strip it and you end up sideways and people end up confused.

[dylan-Images.zip](https://github.com/ExpressionEngine/ExpressionEngine/files/11566800/dylan-Images.zip)

### PR DESCRIPTION
**Pull request by intoeetive**
Resolved #3456 where manipulated images could have wrong rotation

### CODE REVIEW

**Comment by robinsowell** [comment]
@intoeetive This seems to be half fixed.

Testing- I tested on 7.3 dp, just pulled in the 1 updated file.  So... take that for what it's worth.

When I drag/drop the 'bad' image, it now displays properly in publish.  Dylan is right side up.  If I do the same without the fix, Dylan is sideways.

BUT after I save and the page reloads?  Dylan is sideways in the publish display again.  Not sure why that is.  Weird.

**Review by robinsowell — CHANGES_REQUESTED** [review]
Looks good when I drag it in, but after save, is still sideways on publish page.

**Comment by intoeetive** [comment]
@robinsowell are you testing from filemanager page or entry page? (don't know if that matters, but could be)

**Comment by robinsowell** [comment]
Entry page.  So here is me creating an entry.  I pull the 'broken' image into my file field- all looks well:

Screenshot 2023-05-31 at 3 32 07 PM


The I save the entry, page reloads and looks like:

Screenshot 2023-05-31 at 3 32 22 PM

If I go look at the file manager, the thumb is sideways:

Screenshot 2023-05-31 at 3 34 51 PM

If I click the thumb to edit the image, the image looks fine:

Screenshot 2023-05-31 at 3 36 06 PM

Note- this was a 'clean' upload drag and drop in that I made sure there were no filename conflicts or anything.  I just dragged the image over, it did it's little ajaxy thing, and there was Dylan, looking like a good boy in proper orientation.  Then I save and it borks.

**Comment by intoeetive** [comment]
Not replicating it :(

Do you have anything in upload directory settings? Which browser do you use?

**Comment by bryannielsen** [comment]
I'm able to reproduce the same behavior @robinsowell described when using this branch.  Nothing special in my upload directory settings and latest Chrome.  I will try to dig into the code a little and see if I can figure out what's happening since I'm able to replicate.

**Comment by VarenSwaab** [comment]
I'm still having the same issue as described. If I can do any testing or help in any way let me know.

**Comment by intoeetive** [comment]
@VarenSwaab it has not been released yet. If you want to test, you can check out this branch or just use this file in place of your `system/ee/legacy/libraries/Filemanager.php` https://raw.githubusercontent.com/ExpressionEngine/ExpressionEngine/eb132808e16ba9a55fc149c684708cd78d538f8c/system/ee/legacy/libraries/Filemanager.php

Note that existing file manipulations will not be replaced, so you'd need to remove those - or upload new files to test (@bryannielsen  - could that be your issue as well?)

**Comment by robinsowell** [comment]
Man, this one is a bear.  I just retested, I'm running 7.3.4 and I just pulled the Filemanager.php file from the link above.  I used the same dylan wrong file.  This time, I tested in the file manager.  I used the 'upload' button, uploaded it, and it's sideways.  If I open the same image on my mac, it's correct orientation.

Not sure what's going on, but it doesn't appear to be fixed.

**Comment by intoeetive** [comment]
Closing in favor of https://github.com/ExpressionEngine/ExpressionEngine/pull/3569

**Pull request closed without merging**
