### PR TITLE
Revise New/Edit Entry screen title, EECORE-1057

### PR DESCRIPTION
**Pull request by Yulyaswan**
The “New/Edit Entry” title should be placed within a `panel-heading`.
The “Save” and “Preview” buttons should be placed within the same `panel-heading.`
The tab bar should be placed under the `panel-heading` within the `panel-body.`
The `panel-heading` can be made sticky so the save buttons are always in view.

### CODE REVIEW

**Comment by ajohnson** [comment]
@Yulyaswan Left you a comment in the issue regarding problems with these changes conflicting with Pro:

https://packettide.atlassian.net/browse/EECORE-1057?focusedCommentId=15573

**Comment by ajohnson** [comment]
@Yulyaswan Thanks! I made some additional tweaks to the responsive behavior of the publish form save buttons, and some tweaks to the live preview panel. I think this one is good to go!

**Review by ajohnson — DISMISSED** [review]

**Review by intoeetive — COMMENTED** [review]
Technically, I did not spot any issues with this change, however I wonder what problem does it solve? @ajohnson  On my screen, I did not notice any difference in vertical space taken, except for maybe few pixels.

This branch: 
image

6.dev:
image

**Comment by ajohnson** [comment]
@intoeetive This one isn't about saving space. It's part of a continuing effort to bring consistency to the relationship of main section titles and panel titles throughout the CP. Section titles are used when sub-pages exist within a section that have their own titles within a `panel-heading` (e.g. Categories, Members, Fields, etc.).

Our latest work for this was on the main Entries listing screen, removing the main section title, allowing the title within the `panel-heading` to serve as the Entries page title. Possibly more clean-up to come in other parts of the CP.

BUT I am noticing the odd spacing above the tabs on the Publish form. I just pushed a CSS tweak to this branch to address that.

Thanks!

**Review by bryannielsen — DISMISSED** [review]

**Review by intoeetive — APPROVED** [review]

**Pull request merged**
