### PR TITLE
Added options for displaying the grid layout

### PR DESCRIPTION
**Pull request by Yulyaswan**
EECORE-2155
Added 3 options for Grid layout view:

1. Auto (the grid will be placed in a horizontal row and stacked vertically if there is not enough space)
2. Always use a vertical grid layout
3. Always use a horizontal grid layout

### CODE REVIEW

**Comment by intoeetive** [comment]
Marking as draft as it needs same changes as https://github.com/ExpressionEngine/ExpressionEngine/pull/2513

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan for some reason the template routes grid became vertical and is now failing the tests. (this did not happen on 7.x version for this). Can you have a look?

**Review by ops-andy — APPROVED** [review]
looks good in Firefox and Chrome to me

**Comment by ops-andy** [comment]
@robinsowell if you have a really crazy grid test it might be good to test this on it.

**Review by intoeetive — COMMENTED** [review]
worked well on my tests on Grid field and Grid within Fluid.

Cypress tests seem to pass now.

However I also see changes to dropdown JS which I don't know if are intended to be here?

**Review by intoeetive — APPROVED** [review]

**Pull request merged**
