### PR TITLE
Added options for displaying the grid layout

### PR DESCRIPTION
**Pull request by Yulyaswan**
EECORE-2155
EE6 version - #2512
Added 3 options for Grid layout view:

1. Auto (the grid will be placed in a horizontal row and stacked vertically if there is not enough space)
2. Always use a vertical grid layout
3. Always use a horizontal grid layout

### CODE REVIEW

**Review by intoeetive — CHANGES_REQUESTED** [review]
It does not seems to respect previous settings.

I had a grid (used within a Fluid, but I don't know if that makes a difference) set to vertical layout. After I switched to this branch, the grid was displayed horizontally.

Also I think the text for settings needs some changes.
Proposing this:
Grid layout
Choose how the field is displayed on publish pages (in small font)
Auto
Vertical layout
Horizontal layout

If we need extra explanation for "auto" option, it should be in small font (but I don't think we need it)

**Review by intoeetive — CHANGES_REQUESTED** [review]
Vertical now works fine, but setting to "horizontal" behaves same as "auto" - it sets the grid layout to vertical if I narrow the window.

Also another thing I noticed - on vertical layout, the column instructions are italic and black instead of grey.

**Comment by matthewjohns0n** [comment]
I'm pushing this to 7.2.x since there still seem to be changes that are needed on this one.

**Review by intoeetive — DISMISSED** [review]
Looks good for me - do we need extra reviews here @ops-andy ?

**Review by ops-andy — APPROVED** [review]
looks good in Firefox and Chrome to me

**Pull request merged**
