### PR TITLE
Clarified language describing channel

### PR DESCRIPTION
**Pull request by bmackenty**
The pull request hopes to fix issue #203 .Thank you!

## Overview

Replace this paragraph with a description of your changes and reasoning. Provide links to external references/discussions if appropriate.

Resolves [#NN](https://github.com/ExpressionEngine/ExpressionEngine/issues/NN).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pulls/NNN

### CODE REVIEW

**Comment by derekjones** [comment]
Perfect @bmackenty! Can you please make sure you've signed the [CLA](https://www.clahub.com/agreements/ExpressionEngine/ExpressionEngine) so we can legally include your contribution into the project? Thanks!

**Comment by bmackenty** [comment]
I signed the CLA :-)

**Comment by derekjones** [comment]
Thanks Bill, you're an [official contributor](https://github.com/ExpressionEngine/ExpressionEngine/blob/stability/AUTHORS.md) now!

**Comment by bmackenty** [comment]
This is so cool. I look forward to contributing more in the future. It's
such an honor for me to help EE be better.

**Pull request merged**
