### PR TITLE
Direct link to file in file manager

### PR DESCRIPTION
**Pull request by gilbert-hop**
## Overview

Many times we're asked by our clients to enable a button that will show them the direct URLs to the files in the file manager. Currently, you need to click view and then Copy Image Address to get the URL.

## Nature of This Change
Adds a link button to the toolbar for direct access. 

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

### CODE REVIEW

**Comment by gilbert-hop** [comment]
@intoeetive can you please let me know what I'm doing wrong that the test is not passing? Thanks!

**Comment by intoeetive** [comment]
@gilbert-hop the testing script in 6.dev branch has a flaw that prevents third-party PRs from being tested correctly. We'll get this fixed early next year

**Comment by gilbert-hop** [comment]
I noticed that I merged into our stability branch... should I not have done that? Do you want me to send in a pull request on a separate branch?

**Comment by intoeetive** [comment]
@gilbert-hop I think that does not matter a lot - though it might be better if you submit PR from a dedicated feature branch, in case your `stability` gets updated with something else. Also, can you merge latest `6.dev` from `ExpressionEngine/ExpressionEngine` into your branch - that would make the tests run correctly

**Comment by gilbert-hop** [comment]
@intoeetive merged. I asked if I should redo this process with a clean feature branch because we also have other chagnes that we'd like to contribute.

**Comment by intoeetive** [comment]
Then maybe it's best to have separate branch (and separate PR) for each feature

**Pull request closed without merging**
