### PR TITLE
fixed file modal  overlap, EECORE-1498

### LINKED ISSUE #1468: Overlay over file modal (z-index)
Problem happens when publishing an entry.

The publish page contains an RTE field and an file field.

To reproduce the problem:

1 - Insert an image in the RTE field;
2 - Next, in the file field click on "Upload New".

The overlay z-index is greater than the modal.

Printscreen:
overlay

### PR DESCRIPTION
**Pull request by Yulyaswan**
fixes #1468 
EECORE-1498

### CODE REVIEW

**Comment by ops-andy** [comment]
@intoeetive please attach this to a milestone and update the corresponding Jira ticket. thanks!

**Review by intoeetive — CHANGES_REQUESTED** [review]
@Yulyaswan Can you explain why to changed the z-index to fixed number here instead of restoring the previous value? I'm not sure this is the right solution to it

**Comment by Yulyaswan** [comment]
I made z-index empty, to remove it if the modal is closed

**Comment by intoeetive** [comment]
Not feeling confident with it. Will skip for this release, and looking for more reviews

**Review by TomJaeger — APPROVED** [review]

**Review by matthewjohns0n — APPROVED** [review]

**Review by obfuscode — APPROVED** [review]

**Pull request merged**
