### PR TITLE
Add toolbar item to view absolute urls of files

### PR DESCRIPTION
**Pull request by gilbert-hop**
## Overview

Many times we're asked by our clients to enable a button that will show them the direct URLs to the files in the file manager. Currently, you need to click view and then Copy Image Address to get the URL.

## Nature of This Change
Adds a link button to the toolbar for direct access. 

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

### CODE REVIEW

**Comment by gilbert-hop** [comment]
@intoeetive I did some rebasing so hopefully this is good now.

**Comment by intoeetive** [comment]
Looks like the tests failed because some of the icons became not visible.

Can you add these lines to `tests/cypress/cypress.json`?
```
    "viewportWidth": 1024,
    "viewportHeight": 1280,
```

**Comment by intoeetive** [comment]
I am sorry @gilbert-hop , but I've confused width and height. It should be
```
    "viewportWidth": 1280,
    "viewportHeight": 1024,
```
can you make this change?

**Review by intoeetive — APPROVED** [review]
Just noting that I've re-run the tests locally and they all passed. Approving

**Comment by gilbert-hop** [comment]
Hey @intoeetive, what's the status on this?

**Comment by intoeetive** [comment]
I had to resolve the conflicts and fix tests, so closing this PR if favor of new one: https://github.com/ExpressionEngine/ExpressionEngine/pull/2067

**Pull request closed without merging**
