### PR TITLE
Resolves memberlist form attribute issue that remained after #2659/#2689

### PR DESCRIPTION
**Pull request by jHards**
Previous PR only addressed Member Search Form tag and not Memberlist tag (an oversight). Also updated action id to 'member_search' for both tags, as the current 'do_member_search' appears to be a legacy entry.

### CODE REVIEW

**Comment by intoeetive** [comment]
@jHards thank you for this PR!

I am not sure that changing one action to another is the thing we'd want to do however - both seems to be functional (but somewhat different) with both legacy and regular templates

**Comment by jHards** [comment]
@intoeetive am I reading the failed test correctly in that it's an issue with the test rather than this PR?

**Comment by intoeetive** [comment]
The test that's failing is `member_list`, so that must be related to the actual changes in code

**Comment by jHards** [comment]
The test is looking for some table tags that it can't find but I wasn't expecting my changes to affect that - what tag is the test trying to load?

**Comment by intoeetive** [comment]
Do you have access to the test run summary page? There's artifacts sections there, where you can download the zip with the screenshots and videos 
https://github.com/ExpressionEngine/ExpressionEngine/actions/runs/4315756812

**Comment by jHards** [comment]
Got it, thanks. Looks like the user the test script is logged in as doesn't have access to via public member profiles?

Member List frontend -- respects the options (failed) (attempt 2)

**Comment by intoeetive** [comment]
It could be that, or it could be something completely different. Since the error is not clear typo or something that you can see from the screenshot, you would need to set up Cypress locally and run the tests to see yourself, and then figure out what's causing the failure

We have a small section on testing written: https://github.com/ExpressionEngine/ExpressionEngine/blob/7.dev/CONTRIBUTING.md#tests

**Comment by intoeetive** [comment]
@jHards I realize you have dedicated a lot of effort to this PR, but looking into it as we come closer to EE 7.4 release, I don't think this is the change we want to include.

It's trying to submit data to search members in place where the code says member search should not be used. The current submission of select dropdowns in `exp:member:memberlist` tag works fine, so I'm going to close this without merging.

Thank you for all your contributions to members functionality in ExpressionEngine - while we don't always accept those, they help us to become better!

**Comment by jHards** [comment]
@intoeetive Thanks for the explanation. Where I was going with this is that I needed to present a pre-filtered, pre-sorted set of member data but I didn't want to output the whole thing with the search form and let users do it themselves. Have I missed something in the docs or is this something that is in your 7.4 pack of member updates?

**Comment by intoeetive** [comment]
@jHards the tag has `role_id`, `limit`, `orderby` and `sort` parameters (which are not documented - thanks for pointing out). If you need to have better options of filtering using tag parameters, please open a feature request. I also believe some of the add-ons are capable to display more granular member lists

**Comment by jHards** [comment]
@intoeetive see [#3649](https://github.com/ExpressionEngine/ExpressionEngine/discussions/3649)

**Pull request closed without merging**
