### PR TITLE
Added `CP/Form` object layer to generate Shared Form arrays; #2101

### LINKED ISSUE #2101: Shared Form View But With Objects
**Is your feature request related to a problem? Please describe.**
Would make things more fun if we could build forms programmatically. 

**Describe the solution you'd like**
Something like this:

```php
$form = ee('Cp/Form');
$form->asTab();
$form->asFileUpload();
$field_group = $form->getGroup('header 1');
$field_set = $field_group->getFieldSet('first_name');
$field_set->getField('first_name', 'text')
    ->setDisabled(true)
    ->setValue('Eric');

$form->toArray();
```

**Describe alternatives you've considered**
Not writing it, I guess?

**Teachability, Documentation, Adoption, Migration Strategy**
Docs should be written, yes, I agree. The implementation will be backwards compatible and conform to how Shared Form arrays are expected. 

- [x] I am capable and would like to work on implementation of this feature if it is considered.

### PR DESCRIPTION
**Pull request by eric-lamb62**
- (x.X.x) Small additive changes should target the next minor branch (release/next-minor if a numbered branch does not yet exist)

## Overview

Adds an object layer to generate Shared Form arrays. This is a collaboration between @dougblackjr @ops-andy @TomJaeger @jcogs-design @stephengalbraith @robinsowell @mithra62 and Blair Liikala (whom I can't find a Github for as I'm writing this 😢). 

Resolves [#2101](https://github.com/ExpressionEngine/ExpressionEngine/issues/2101).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [x] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/462

### CODE REVIEW

**Comment by eric-lamb62** [comment]
Should be noted this requires PHP 7.1

**Comment by eric-lamb62** [comment]
Here's a rather full fledged, copy/paste, example of how this works:

```php
$form = ee('Cp/Form');
$form->asTab();
$form->asFileUpload();
$field_group = $form->getGroup('header 1');
$field_set = $field_group->getFieldSet('first_name');
$field_set->getField('first_name', 'text')
    ->setDisabled(true)
    ->setValue('Eric');

$field_set = $field_group->getFieldSet('last_name')->withButton('Click Me');
$field_set->getField('last_name', 'text')
    ->setPlaceholder('Last Name')
    ->setRequired(true);
$form->setCpPageTitle('Hello!');

$field_group = $form->getGroup('Custom Input Example');
$field_set = $field_group->getFieldSet('email');
$field_set->getField('email', 'email')
    ->setPlaceholder('Your Email Address')
    ->setValue('eric@mithra62.com')
    ->setRequired(true);

$field_set = $field_group->getFieldSet('color');
$field_set->getField('color', 'color')->setValue('#C86565');

$field_set = $field_group->getFieldSet('number');
$field_set->getField('number', 'number')->params(['min' => 100, 'max' => 1000])->setRequired(true);

$field_group = $form->getGroup('Contact details');
$field_set = $field_group->getFieldSet('Address');
$field_set->getField('address1', 'text');
$field_set->getField('address2', 'action_button')->setText('Hello');
$field_set->getField('state', 'dropdown')->withNoResults('Nothing Here', 'fdsa', 'fdsa');

$form->withActionButton('My Action Button', 'https://google.com');
$button = $form->getButton('button_1');
$button->setType('submit')->setText('Submit Button')->setWorking('Submitting...');

$form->getButton('button_2');
$form->removeButton('button_2');

$hidden_field = $form->getHiddenField('my_hidden_field');
$hidden_field->setValue('my_value');

$field_group = $form->getGroup('Table Example');
$field_set = $field_group->getFieldSet('My Table Data');
$table = $field_set->getField('my_table', 'table');

$table->setOptions([
    'lang_cols' => true,
    'class' => 'product_channels'
]);

$table->setColumns([
    'details' => ['sort' => false],
    'value' => ['sort' => false],
]);

$table->setNoResultsText(sprintf(lang('no_found'), lang('product_channels')));
$table->setBaseUrl( ee('CP/URL')->make($this->base_url ));
$data = [];
$data[] = [
    'Hello',
    'You',
];

$table->setData($data);
$table->addRow([
    'No, Hello',
    'To You!',
]);

$field_group = $form->getGroup('Filepicker Example');
$field_set = $field_group->getFieldSet('My Filepicker');
$file_picker = $field_set->getField('my_file_picker', 'file-picker');
$file_picker->asImage()->withDir(7)->setValue('{filedir_7}path.jpg');

$field_group = $form->getGroup('Grid Example');
$field_set = $field_group->getFieldSet('My Grid')->withGrid();
$grid = $field_set->getField('my_grid_field', 'grid');

$grid->setOptions([
    'field_name' => $grid->getName(),
    'reorder'    => true,
]);

$grid->setColumns([
    'text example' => ['sort' => false],
    'select example' => ['sort' => false],
    'password example' => ['sort' => false],
    'checkbox example' => ['sort' => false],
    'textarea example' => ['sort' => false],
    'upload example' => ['sort' => false],
]);

$options = ['foo' => 'Foo', 'bar' => 'Bar'];
$cols = [
    ['name' => 'foo-text', 'type' => 'text', 'value' => ''],
    ['name' => 'barr-select', 'type' => 'select', 'value' => '', 'choices' => $options],
    ['name' => 'foo-password', 'type' => 'password', 'value' => ''],
    ['name' => 'bar-checkbox', 'type' => 'checkbox', 'value' => 1],
    ['name' => 'foo-textarea', 'type' => 'textarea', 'value' => '', 'cols' => 2, 'rows' => 5],
    ['name' => 'bar-upload', 'type' => 'file', 'value' => '', 'cols' => 2, 'rows' => 5],
];
$grid->defineRow($cols);
$grid->setData([
    ['foo-text' => 'bar', 'barr-select' => 'foo', 'foo-password' => 'fdsa', 'bar-checkbox' => 1, 'foo-textarea' => '', 'bar-upload' => ''],
    ['foo-text' => 'fdsafdsa', 'barr-select' => 'bar', 'foo-password' => 'fdsa', 'bar-checkbox' => true, 'foo-textarea' => '', 'bar-upload' => '']
]);

$grid->setNoResultsText(sprintf(lang('no_found'), lang('table-thing')), 'add');
$grid->setBaseUrl( ee('CP/URL')->make($this->base_url ));

$test_form = $form->toArray();
```

**Comment by litzinger** [comment]
Not sure I want to be _that_ guy, but this is a lot of new code to be adding... any unit tests?

**Comment by eric-lamb62** [comment]
@litzinger oh no, please do be _that_ guy; good question and we _need_ tests for systems like this.  But yes, there are quite a few waiting to be integrated. Problem is the current dev branches test suite fails on the Table tests (unrelated to this) so I couldn't integrate them as yet. 

image

Once we can get that resolved I can port the tests over all easy peasy.

**Comment by litzinger** [comment]
the-simpsons-mr-burns

**Comment by eric-lamb62** [comment]
@litzinger I forgot I knew how phpunit.xml works; I've uploaded the tests I had. It's only 158 tests and 258 assertions atm

image

They pass, but as mentioned, the complete suite does not, so adjustments should be made to phpunit.xml if anyone wants to run them. It's only about 60% coverage FWIW but I want to hold off on locking everything down until a consensus can be reached on the API and such.

**Comment by eric-lamb62** [comment]
We should have complete test coverage for all the code that doesn't contain any calls to `View`, `Table`, `Grid`, and any of the `form_helper` functions. Those all fail due to what appears to be generic bootstrap issues and that functionality not being loaded (or loadable idk). I attempted to debug but that quickly became way over my pay grade so I leave it here. 

Couple things worth mentioning:

1. There's very little magic outside of a couple areas. All the properties for creating a Shared Form are handled specifically to their domain and generally correspond to a hard-coded key within the object.  See the `prototype` property as an example. Point being, we've opted for verbosity over being clever.
2. The implementation is built surrounding the existing implementation laid out in `ee:_shared/form` and how it expects data to be presented. While we were able to add new features/fields through the implementation this should be backwards compatible with any EE that includes Shared Form (idk the versions).  
3. The bundled `Table`, `Grid`, and `Filepicker` fields are built around simplifying their implementation into a Shared Form. They are slimmed down implementations though they also have some benefits. For example, the `Grid` field will automatically handle POST data and field generation using (ironically enough) a syntax similar to the current Shared Form (but for Grid). But there are drawbacks; you're limited to the input fields that EE has within the `form_helpers` functions. Still, if a dev wants to go full control they still have the option; this is just to cover 90% of the use cases. 

If there are any changes, notes, or questions please @ me; what we do next is up to someone else.

**Review by intoeetive — APPROVED** [review]
This has been already included into EE 7.0, and now we need it in EE 6.4.0 where it was originally intended. Approving

**Pull request merged**
