### PR TITLE
Adding HTTP Methods addon

### LINKED ISSUE #413: Add template tags for GET variables
**Is your feature request related to a problem? Please describe.**
Currently the EE template system requires a third-party add-on to use GET parameters from a URL in a template

**Describe the solution you'd like**
Would be nice to have GET variables natively in the template parser in a logical way.

FR created from conversation in EE Slack.

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

Adds new core add-on called HTTP Methods, which allows for a user to get the following in their templates:

```
<p>get: {exp:http_methods:get name="test"}</p>
<p>post: {exp:http_methods:post name="test"}</p>
<p>get_post: {exp:http_methods:get_post name="test"}</p>
<p>cookie: {exp:http_methods:cookie name="test"}</p>
<p>ip_address: {exp:http_methods:ip_address}</p>
<p>user_agent: {exp:http_methods:user_agent}</p>
<p>request_header: {exp:http_methods:request_header name="accept"}</p>
```

Resolves [#413](https://github.com/ExpressionEngine/ExpressionEngine/issues/413).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [X] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/168

### CODE REVIEW

**Comment by obfuscode** [comment]
@dougblackjr Would you be able to PSR-12 this as well? Looks like there's mixed whitespace and such in the add-on files.

**Comment by dougblackjr** [comment]
@obfuscode Updated!

**Review by obfuscode — APPROVED** [review]

**Comment by intoeetive** [comment]
@dougblackjr @obfuscode @TomJaeger I know I'm kinda late for the party, but will just throw this in here.

I think if the add-on would be named just `http` that would sound better:
```
<p>get: {exp:http:get name="test"}</p>
<p>post: {exp:http:post name="test"}</p>
<p>get_post: {exp:http:get_post name="test"}</p>
<p>cookie: {exp:http:cookie name="test"}</p>
<p>ip_address: {exp:http:ip_address}</p>
<p>user_agent: {exp:http:user_agent}</p>
<p>request_header: {exp:http:request_header name="accept"}</p>
```

**Comment by TomJaeger** [comment]
My gut reaction is that this is a good idea / a good catch.  for programmers _method doesn't present any issues etc... but a lot of people who use EE that would be a bit foreign to as a whole.

**Comment by obfuscode** [comment]
@intoeetive Do you want to take care of this or should we kick it back to Doug to update?

**Comment by intoeetive** [comment]
@obfuscode I can do it (but likely will be able to only next week) - unless @dougblackjr wants to handle this himself so it would be "fully his" code. Would you mind creating task in Jira?

**Comment by dougblackjr** [comment]
@obfuscode @intoeetive @TomJaeger My thought behind naming it this way was to follow the same schema as HTTP Header (https://docs.expressionengine.com/latest/add-ons/http-header.html#http-header). My fear is that changing this to `http` may be confusing. It's an easy change, but I want to make sure it serves the user well. What do y'all think?

**Comment by intoeetive** [comment]
So now that we have this bigger and better add-on, should we consider deprecating HTTP Header add-on and moving it's functionality into the new one?

**Comment by dougblackjr** [comment]
@intoeetive I'm not sure, I like having them separate, since they have distinctly separate functions. HTTP Header sends something in the call, HTTP Method gets something from the HTTP call.

**Pull request merged**
