### PR TITLE
Add hook_id to Channel model

### PR DESCRIPTION
**Pull request by litzinger**
## Overview

The Channel model does not currently publish even hooks when a channel is created, updated, or deleted. As an add-on developer it would be nice to be able to subscribe to these events.

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by derekjones** [comment]
Agreed! Retargeted `5.3.0` as semver prefers additive changes to be in major or minor rather than in patch releases. Simpler for add-ons to target as a minimum requirement if need be as well. Thanks @litzinger!

**Comment by derekjones** [comment]
Do you have time to put in a PR to the docs as well? https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/tree/stability/docs/development/extension-hooks/model

**Comment by litzinger** [comment]
I _might_ request a few more to things... let me know if these are good or bad ideas :)

- ChannelFormSettings (not 100% sure what that does yet)
- ChannelLayout
- Site
- RevisionTracker
- SpecialtyTemplate
- Snippet
- GlobalVariable

I think that would complete the list of things people might need to migrate from one database to another (dev to prod for example).

**Comment by litzinger** [comment]
Yeah, I'll try to update the docs too.

**Comment by derekjones** [comment]
`ChannelFormSettings` stores the Channel's preferences for Channel Form (guest author, etc.) so I agree, that would be good to include as well.

**Pull request merged**
