### PR TITLE
Parse file paths on query module

### LINKED ISSUE #1400: Parse file directories on `exp:query` module
**Is your feature request related to a problem? Please describe.**
Why not? Isn't one of the great features of eecms to be flexible?

**Describe the solution you'd like**
Clear and concise? Ok!

```
        if (strpos($str, '{filedir_') !== false) {
            ee()->load->library('file_field');
            $str = ee()->file_field->parse_string($str);
        }
```

**Describe alternatives you've considered**
Alternatives? Get only the IDs and nest a `exp:channel:entries`! (Die, performance! Die!)

**Teachability, Documentation, Adoption, Migration Strategy**
I guess, it would work automagically, right?

- [x] I am capable and would like to work on implementation of this feature if it is considered.

### PR DESCRIPTION
**Pull request by robsonsobral**
Adding `parse_files` parameter

## Overview

Replace this paragraph with a description of your changes and reasoning. Provide links to external references/discussions if appropriate.

Resolves [#1400](https://github.com/ExpressionEngine/ExpressionEngine/issues/1400).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/268

### CODE REVIEW

**Comment by robsonsobral** [comment]
If somebody knows how to parse manipulations and modifiers, please tell.

**Comment by robsonsobral** [comment]
Do you want me to allow multiple values to the [`parse` parameter](https://github.com/ExpressionEngine/ExpressionEngine/blob/050499c09ce34fd0268459e34afb6a819cf3131d/system/ee/legacy/libraries/Template.php), @intoeetive , so we can follow the path you suggested in a future update?

**Comment by intoeetive** [comment]
I honestly don't know. I initially though we could have parsing like this globally working as modifiers, but that turned to contain some underwater stones.

Since this PR has been pre-approved in https://github.com/ExpressionEngine/ExpressionEngine/issues/1400 by @TomJaeger I tend to just include it for now and then go with other things separately.

**Review by intoeetive — DISMISSED** [review]

**Comment by robsonsobral** [comment]
Let's merge it, @TomJaeger ?

**Review by TomJaeger — APPROVED** [review]

**Pull request merged**
