### PR TITLE
properly handle arrays of variables with Request plugin

### LINKED ISSUE #1426: Request module doens't know how to deal with an array
In case of a query string like `/test/?category[]=4&category[]=5&category[]=6`, we get:

```
Array to string conversion

ee/legacy/libraries/Template.php, line 1728

    Severity: E_NOTICE
```

And just `Array` is printed.

Shouldn't it return `4|5|6`, the infamous eecms array notation?

### PR DESCRIPTION
**Pull request by intoeetive**
fixes #1426

EECORE-1457

### CODE REVIEW

**Review by obfuscode — APPROVED** [review]

**Comment by robsonsobral** [comment]
I just tested it and... I'm sorry, guys, but I disagree on the solution!

```
<pre>
debug of exp:request:get name="category"

    {exp:request:get name="category"}
</pre>
```

Gives:

```
<pre>debug of exp:request:get name="category"

    1
2
3
4
5

</pre>
```

As this is a template module, this intention should be to serve data to the template module.
At least, when used as single variable, the output should be `1|2|3|4|5`.

**Comment by robsonsobral** [comment]
Even worst! The code is bugged!

```<pre>
exp:request:get name="category"

    {exp:request:get name="category"}
</pre>

<pre>
exp:request:get name="category"

{exp:request:get name="category"}
    {item}
{/exp:request:get}
</pre>
```

Gives:

image

Jesus!

**Comment by intoeetive** [comment]
The intended usage here is the tag pair. But I can see the point fo adding `delimiter` as param here

Regarding your other comment, unfortunately using same tag as single tag and tag pair in same template will cause issues with any add-on. It's EE parser problem in general

**Comment by intoeetive** [comment]
@robsonsobral https://github.com/ExpressionEngine/ExpressionEngine/pull/1454

**Comment by robsonsobral** [comment]
Ok! Now, it's approved! (Just kidding!)

**Pull request merged**
