### PR TITLE
Add setting for turning off the CLI

### PR DESCRIPTION
**Pull request by matthewjohns0n**
## Overview

Adds a setting for disabling the CLI.

EECORE-1388

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

### CODE REVIEW

**Comment by TomJaeger** [comment]
@matthewjohns0n It looks like we have some failing tests on this one.  Any chance you can look into those?

**Comment by matthewjohns0n** [comment]
@TomJaeger I pulled the failed archives, but it doesn't look to be related to these changes at all. Maybe @intoeetive has more insight into this?

I thought maybe it had something to do with the tests, so I merged the latest `6.dev` branch and pushed that up, since it would trigger the tests. Unfortunately, the tests only run when the PR is into `6.dev` so no tests ran. I think to trigger the tests again we need the PR to change the PR to 6.dev.

**Comment by intoeetive** [comment]
@matthewjohns0n I've updated the workflow file to run tests on this branch as well

**Comment by intoeetive** [comment]
So the installer tests failed, because there is mismatch on the version - the updater file for 6.2.0 is present in change, however the version in all files is still kept as 6.1.6. This is not correct, if the version is being updated, it should be changed in multiple places.

Maybe for this particular case we can ignore this however, as we know these changes already exist in other branches (and the rest of the tests succeeded)

**Comment by TomJaeger** [comment]
Re-ran the tests... still failing.

**Comment by matthewjohns0n** [comment]
I merged the latest `6.2.0` branch and now the tests are passing.

**Review by obfuscode — APPROVED** [review]

**Pull request merged**
