### PR TITLE
make overflow scrollable when editing entries

### PR DESCRIPTION
**Pull request by acalvino4**
## Overview

This fixes a small UI bug noted in [#1429](https://github.com/ExpressionEngine/ExpressionEngine/issues/1429).
It's not the cleanest fix ever, but it's better than before. I searched through everything in the cp-styles folder, and didn't find any instances of the `tab` class that I modified apart from the places I was intending to change. (I used this regex `[^\\_-]tab[^lRa\-s]` for the search).

## Nature of This Change

- [x] 🐛 Fixes a bug
- [ ] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

### CODE REVIEW

**Comment by intoeetive** [comment]
Thank you for your submission!

Would you mind running `npm run build:css` in the project root? This will build the minified CSS

**Comment by acalvino4** [comment]
yep, I'll do that and submit an update in the next couple days

**Comment by acalvino4** [comment]
Build failed for me with below output. I am using Node 14.18.1 on MacOS 11.4. Are there other specific steps or software reqs to make it work?

```
../src/create_string.cpp:17:25: error: no matching constructor for initialization of 'v8::String::Utf8Value'
  v8::String::Utf8Value string(value);
                        ^      ~~~~~
/Users/acalvino4/.node-gyp/14.18.1/include/node/v8.h:3294:5: note: candidate constructor not viable: no known conversion from 'v8::Local<v8::Value>' to 'const v8::String::Utf8Value' for 1st argument
    Utf8Value(const Utf8Value&) = delete;
    ^
/Users/acalvino4/.node-gyp/14.18.1/include/node/v8.h:3287:5: note: candidate constructor not viable: requires 2 arguments, but 1 was provided
    Utf8Value(Isolate* isolate, Local<v8::Value> obj);
    ^
1 warning and 1 error generated.
make: *** [Release/obj.target/binding/src/create_string.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/acalvino4/Code/web-frameworks/ee/ExpressionEngine/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at ChildProcess.emit (events.js:400:28)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:282:12)
gyp ERR! System Darwin 20.5.0
gyp ERR! command "/Users/acalvino4/.nvm/versions/node/v14.18.1/bin/node" "/Users/acalvino4/Code/web-frameworks/ee/ExpressionEngine/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /Users/acalvino4/Code/web-frameworks/ee/ExpressionEngine/node_modules/node-sass
gyp ERR! node -v v14.18.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
Build failed with error code: 1
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-sass@4.9.4 postinstall: `node scripts/build.js`
npm ERR! Exit status 1
```

**Comment by intoeetive** [comment]
That looks like generic problem with Node.js
I am using version 10.22.1, I see you're using v14.18.1 - so maybe worth trying different version

**Comment by intoeetive** [comment]
@acalvino4 thank you for the work on this!

We took your idea further and worked on another fix internally, which we think will work better: https://github.com/ExpressionEngine/ExpressionEngine/pull/1507

I will have to close this PR without merging, but I'd like to stress again that we really appreciate the efforts you have done here!

**Comment by acalvino4** [comment]
No worries, whatever makes the product best!

**Pull request closed without merging**
