### PR TITLE
Bring back default order field

### LINKED ISSUE #1258: Fallback order of fields to "old way"
**Is your feature request related to a problem? Please describe.**
The layouts of channels are powerful to use, but hard to customize.

**Describe the solution you'd like**
I would like to be able to set the order of the fields on the fields themselves, like the old way. It don't, of course, need to use the old number fields, but a drag and drop within the groups. They would be the default value to be used in case of no layouts.

- [x] I am capable and would like to work on implementation of this feature if it is considered.

### PR DESCRIPTION
**Pull request by robsonsobral**
## Overview

Because to have to edit layouts one by one is too much work. It isn't a fancy drag and reorder thing, but is much better than to have to open layouts again, again and again for every channel.

Maybe the field description needs an update.

Resolves [#1258](https://github.com/ExpressionEngine/ExpressionEngine/issues/1258).

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [x] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [x] Yes
- [ ] No

## Documentation

User Guide Pull Request: https://github.com/ExpressionEngine/ExpressionEngine-User-Guide/pull/NNN

### CODE REVIEW

**Comment by intoeetive** [comment]
@ajohnson can you review this? 
It's adding back the functionality that was removed at some point - however I wonder if there has been specific reasoning on removing it. (Maybe intended to replace with drag&drop sorting? Which is not there - yet - however)

**Comment by robsonsobral** [comment]
@ajohnson , to make your job easier:

image

**Comment by ajohnson** [comment]
@robsonsobral @intoeetive It seems innocent enough to bring back the "Field Order" field to the New/Edit Field form. It was removed in EE 3 with the (then) new Channel Layouts taking its place.

But I'm honestly not sure if there are unintended consequences to bringing it back? Not sure why they removed it to begin with. Maybe some kind of nested logic edge case conflict they were trying to avoid with Channel Layouts?

Also if we bring back the Field Order will users expect to be able to view and sort their list of fields by field order like was available in EE 2?

Screen Shot 2021-11-10 at 2 34 53 PM

All this to say I'm fine with bringing back the "Field Order" field, but I don't trust myself alone to test this for potential errors/conflicts. We'd probably want to the team to jump into testing a bunch of random scenarios on this one since custom fields are such a high profile feature of EE.

@TomJaeger Do you recall any history here as to why the Field Order field was removed in the first place?

**Comment by robsonsobral** [comment]
I don't see how it could be currently to sort the fields on CP. However, they should never be removed as they provide a starting point to the Channel Layouts (which should have names on their buttons).

One more thing! They were never removed from database or fields ordering. Just from the interface.

**Comment by intoeetive** [comment]
We had discussion on this internally.

The "sort order" field was removed with introduction of Channel Layouts, which is intended to serve as replacement.

We have agreed that the Channels UI would benefit from some improvements, however we would rather want to address those in complex. Input for field order is a legacy thing and we don't want to reintroduce it.

**Comment by robsonsobral** [comment]
I'm disappointed that the team which runs the project doesn't use it. Otherwise, it would know my reasons to bring this back aren't frivolous.😒

**Pull request closed without merging**
