### PR TITLE
Adding password field toggle

### PR DESCRIPTION
**Pull request by dougblackjr**
## Overview

This adds an icon to toggle the password input on the login screen, so that users can choose whether to view their passwords as they type.

## Nature of This Change

- [ ] 🐛 Fixes a bug
- [X] 🚀 Implements a new feature
- [ ] 🛁 Refactors existing code
- [ ] 💅 Fixes coding style
- [ ] ✅ Adds tests
- [ ] 👽 Adds new dependency
- [ ] 🔥 Removes unused files / code
- [ ] 🔒 Improves security 

## Is this backwards compatible?

- [X] Yes
- [ ] No

### CODE REVIEW

**Comment by dougblackjr** [comment]
Preview here: https://user-images.githubusercontent.com/6020323/137477575-6ed5ad29-9325-4dd6-bf7a-67b74506a5ec.mp4

**Comment by intoeetive** [comment]
@ajohnson can you review this style-wise?

(I also think we need to remove the inline CSS etc)

**Comment by ajohnson** [comment]
@intoeetive @dougblackjr Nice!

I pushed some styling updates to that branch which tweaks the icon color, and uses the same icon set we're using throughout the rest of the CP. (Also moved the inline CSS to our SCSS files.)

Here's what it looks like:
Screen Shot 2021-10-15 at 11 37 47 AM

**Review by intoeetive — DISMISSED** [review]
Tested in Chrome, FF and Edge. All looks good

**Review by intoeetive — APPROVED** [review]

**Pull request merged**
